# Generated by Django 5.1.6 on 2025-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='Sin nombre', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
