# Generated by Django 5.1.7 on 2025-03-30 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaciones', '0005_medicacion_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxima_toma', models.DateTimeField()),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaciones.medicacion')),
            ],
        ),
    ]
