# Generated by Django 5.1.6 on 2025-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='proxima_toma',
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='mensaje',
            field=models.CharField(default='2025-01-01 00:00:00', max_length=255),
            preserve_default=False,
        ),
    ]
