# Generated by Django 5.1.7 on 2025-04-25 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_alter_alerta_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='alerta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
