# Generated by Django 5.1.7 on 2025-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_alter_alerta_options_remove_alerta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=10),
        ),
    ]
