# Generated by Django 5.1.7 on 2025-03-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primera_vez',
            field=models.BooleanField(default=True),
        ),
    ]
