# Generated by Django 5.1.7 on 2025-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_primera_vez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='2000-01-01', help_text='Número de contacto obligatorio', max_length=15, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
