# Generated by Django 5.1.7 on 2025-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicionglucosa',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
