# Generated by Django 5.1.6 on 2025-03-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionGlucosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_glucosa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_medicion', models.CharField(choices=[('Ayunas', 'Ayunas'), ('Postprandial', 'Postprandial'), ('Antes de dormir', 'Antes de dormir')], max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
