# Generated by Django 5.1.6 on 2025-03-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaciones', '0002_medicacion_delete_medicionglucosa'),
        ('pacientes', '0002_paciente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicacion',
            name='paciente',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
