# Generated by Django 5.1.7 on 2025-04-25 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaciones', '0005_medicacion_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
