# Generated by Django 5.1.7 on 2025-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaciones', '0006_medicacion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacion',
            name='zona_horaria',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
