# Generated by Django 5.1.7 on 2025-04-25 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaciones', '0007_medicacion_zona_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicacion',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Hora en la que se debe tomar la primera dosis'),
            preserve_default=False,
        ),
    ]
